"use client";

import dynamic from "next/dynamic";
import type { AppData } from "@/types";

const MermaidDiagram = dynamic(() => import("@/components/MermaidDiagram"), { ssr: false });

interface Props {
  data: AppData;
  onBack: () => void;
  onCopy: () => Promise<void>;
  onDownloadPdf: () => Promise<void>;
  copyFeedback: boolean;
  printRef: React.RefObject<HTMLDivElement | null>;
}

export default function OutputScreen({ data, onBack, onCopy, onDownloadPdf, copyFeedback, printRef }: Props) {
  const generatedDate = new Date().toLocaleDateString("en-US", {
    month: "long", day: "numeric", year: "numeric",
  });

  return (
    <div className="min-h-screen flex flex-col">
      {/* Sticky navbar */}
      <nav className="sticky top-0 z-50 flex items-center justify-between px-8 py-4 border-b border-border bg-bg/90 backdrop-blur-md">
        <button
          onClick={onBack}
          className="flex items-center gap-1.5 text-sm text-text-secondary hover:text-text-primary hover:bg-surface-high px-3 py-1.5 rounded-pill transition-all"
        >
          <ChevronLeft /> Back
        </button>
        <div className="flex items-center gap-1.5">
          <span className="font-display font-extrabold tracking-[0.12em] text-sm text-text-primary">LECTRA</span>
          <span className="text-accent">•</span>
        </div>
      </nav>

      {/* Two-column layout */}
      <div className="flex-1 max-w-6xl w-full mx-auto px-8 py-10 grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-10 items-start">

        {/* ── Left: Main content ── */}
        <div ref={printRef} className="flex flex-col gap-10">

          {/* Title block */}
          <div className="flex flex-col gap-2">
            <span className="font-mono text-[10px] tracking-[0.2em] text-text-muted uppercase">
              Lecture Notes
            </span>
            <h1 className="font-display text-3xl font-extrabold text-text-primary leading-tight">
              {data.title}
            </h1>
            <p className="text-sm text-text-secondary">
              Generated on {generatedDate}
              {data.topic && <> · <strong className="text-text-primary">{data.topic}</strong></>}
            </p>
          </div>

          {/* Action bar */}
          <div className="flex gap-3">
            <ActionButton onClick={onDownloadPdf} id="download-pdf-btn">
              <DownloadIcon /> Download PDF
            </ActionButton>
            <ActionButton onClick={onCopy} id="copy-notes-btn">
              {copyFeedback ? (
                <><CheckIcon className="text-accent" /> <span className="text-accent">Copied!</span></>
              ) : (
                <><ClipboardIcon /> Copy Notes</>
              )}
            </ActionButton>
          </div>

          {/* Notes */}
          <section className="flex flex-col gap-1">
            <span className="section-tag">Notes</span>
            {data.notes.map((section, i) => (
              <div key={i} className="mb-7 last:mb-0">
                <h2 className="font-display text-[17px] font-bold text-text-primary mb-3">
                  {section.heading}
                </h2>
                <ul className="flex flex-col gap-2">
                  {section.bullets.map((bullet, j) => (
                    <li key={j} className="flex gap-3 text-sm text-text-primary leading-relaxed">
                      <span className="text-text-muted text-base mt-0.5 flex-shrink-0">·</span>
                      {bullet}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </section>

          {/* Summary */}
          <section className="flex flex-col gap-1">
            <span className="section-tag">Summary</span>
            <div className="border-l-2 border-accent bg-accent/[0.04] rounded-r-sm px-5 py-4">
              <p className="text-sm text-text-primary leading-[1.8]">{data.summary}</p>
            </div>
          </section>

          {/* Key Takeaways */}
          <section className="flex flex-col gap-1">
            <span className="section-tag">Key Takeaways</span>
            <ul className="flex flex-col gap-3.5">
              {data.keyTakeaways.map((item, i) => (
                <li key={i} className="flex items-start gap-3 text-sm text-text-primary leading-relaxed">
                  <span className="text-accent text-[10px] mt-1.5 flex-shrink-0">●</span>
                  {item}
                </li>
              ))}
            </ul>
          </section>

          {/* Credit */}
          <p className="font-mono text-[10px] text-text-muted text-center tracking-[0.1em] pt-2 border-t border-border">
            Generated by Lectra ✦
          </p>
        </div>

        {/* ── Right: Sidebar ── */}
        <aside className="lg:sticky lg:top-24 flex flex-col gap-5">

          {/* Diagram */}
          <SideCard>
            <span className="section-tag">Diagram</span>
            <div className="bg-bg border border-border rounded-md p-4 min-h-[140px] overflow-auto">
              <MermaidDiagram chart={data.mermaid} />
            </div>
            <p className="text-[11px] text-text-muted mt-2.5">
              Concept map generated from lecture content
            </p>
          </SideCard>

          {/* Stats */}
          <SideCard>
            <span className="section-tag">Stats</span>
            <div className="flex flex-col gap-4">
              <StatRow label="Words Transcribed" value={data.wordCount.toLocaleString()} />
              <StatRow label="Note Sections" value={String(data.notes.length)} />
              <StatRow label="Key Takeaways" value={String(data.keyTakeaways.length)} />
              {data.topic && (
                <StatRow label="Topic" value={data.topic} accent />
              )}
            </div>
          </SideCard>
        </aside>
      </div>
    </div>
  );
}

/* ── Reusable sub-components ── */

function SideCard({ children }: { children: React.ReactNode }) {
  return (
    <div className="bg-surface border border-border rounded-lg p-5 flex flex-col">
      {children}
    </div>
  );
}

function StatRow({ label, value, accent }: { label: string; value: string; accent?: boolean }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="font-mono text-[9px] tracking-[0.18em] text-text-muted uppercase">{label}</span>
      <span className={`font-display text-lg font-bold ${accent ? "text-accent text-sm" : "text-text-primary"}`}>
        {value}
      </span>
    </div>
  );
}

function ActionButton({ onClick, children, id }: {
  onClick: () => void;
  children: React.ReactNode;
  id?: string;
}) {
  return (
    <button
      id={id}
      onClick={onClick}
      className="btn-pill bg-surface border border-border text-text-secondary hover:text-text-primary hover:bg-surface-high hover:border-accent/30"
    >
      {children}
    </button>
  );
}

/* ── Icons ── */
function ChevronLeft() {
  return (
    <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <polyline points="15 18 9 12 15 6" />
    </svg>
  );
}

function DownloadIcon() {
  return (
    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
  );
}

function ClipboardIcon() {
  return (
    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <rect x="9" y="9" width="13" height="13" rx="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function CheckIcon({ className }: { className?: string }) {
  return (
    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className={className}>
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}
